### PR TITLE
Fixed auto start issue

### PR DESCRIPTION
**Pull request by nelwang**
Updated hook point in AutoStartFix to address the issue that app won't be able to receive notification without auto start enabled in app config. 

Now app can receive notification even if auto start is disabled. 

Test steps
1. Disable auto start in app config
2. Force stop app
3. Send notification from other devices
4. Confirm notification can be received on device w/ Android 14/Hyper OS

### CODE REVIEW

**Comment by Rakau** [comment]
安卓14已经正常

**Comment by TigerBeanst** [comment]
感觉好像还是拉不起来……

**Comment by kooritea** [comment]
把services.jar发下吧。。

**Comment by TigerBeanst** [comment]
> 把services.jar发下吧。。

services 和 framework

https://tmp.link/f/655f20874deb7

**Comment by kooritea** [comment]
> > 把services.jar发下吧。。
> 
> services 和 framework
> 
> https://tmp.link/f/655f20874deb7

只能找到自启相关的接口找不到实现了，可能移到哪个系统应用上管理了

**Pull request merged**
